---
title: "Research"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My full CV is available [here](cv_files/Strochak_CV_Nov2018.pdf).

### Publications

**Strochak, Sarah**, Aaron Shroyer, Jung Hyun Choi, Kathryn Reynolds, and Laurie Goodman. 2020. [How Much Assistance is Needed to Support Renters through the COVID-19 Crisis?](https://www.urban.org/research/publication/how-much-assistance-needed-support-renters-through-covid-19-crisis) Washington, DC: Urban Institute.

**Strochak, Sarah**, Jung Hyun Choi, and Laurie Goodman. 2020. [The Impacts of US Military Service on Homeownership and Income](https://www.urban.org/sites/default/files/publication/101495/the_impacts_of_us_military_service_on_homeownership_and_income_1.pdf). Washington, DC: Urban Institute.

McCargo, Alanna, Bing Bai, Taz George, and **Sarah Strochak**. 2018. [Small Dollar Mortgages for Single-Family Residential Properties.](https://www.urban.org/research/publication/small-dollar-mortgages-single-family-residential-properties) Washington, DC: Urban Institute.

### Blog posts

**Sarah Strochak**, ["Moving to a 70 Percent Income Replacement for Unemployment Insurance Benefits Will Disproportionately Hurt Low-Income Renters,"](https://www.urban.org/urban-wire/moving-70-percent-income-replacement-unemployment-insurance-benefits-will-disproportionately-hurt-low-income-renters) Urban Wire (blog), Urban Institute, July 31, 2020.

**Sarah Strochak**, Laurie Goodman, and Sheryl Pardo, ["Is the Sudden Increase in Black Homeownership Too Good to Be True?"](https://www.urban.org/urban-wire/sudden-increase-black-homeownership-too-good-be-true) Urban Wire (blog), Urban Institute, February 4, 2020.

Laurie Goodman, Edward Golding, and **Sarah Strochak**, [“Cash-out refinancing is on the rise again. Here’s why we aren’t worried,”](https://www.urban.org/urban-wire/cash-out-refinancing-rise-again-heres-why-we-arent-worried) Urban Wire (blog), Urban Institute, October 29, 2018.

**Sarah Strochak**, [“How to Create State and County Maps Easily in R,”](https://medium.com/@urban_institute/how-to-create-state-and-county-maps-easily-in-r-577d29300bb2) Data@Urban (blog), Urban Institute, July 10, 2018.

Alanna McCargo and Sarah Strochak, [“Mapping the black homeownership gap,”](https://www.urban.org/urban-wire/mapping-black-homeownership-gap) Urban Wire (blog), Urban Institute, February 26, 2018.

**Sarah Strochak** and Bhargavi Ganesh, [“Visualizing Hurricane Harvey’s impact on Houston’s neighborhoods,”](https://www.urban.org/urban-wire/visualizing-hurricane-harveys-impact-houstons-neighborhoods) Urban Wire (blog), Urban Institute, September 13, 2017.

### Presentations

[Housing and Land Use Implications of Proposed Split Roll Tax Reform](https://www.urban.org/events/how-changes-property-taxes-shape-communities-two-case-studies), August 6, 2020. Urban Institute.

### In the news

Liam Dillon, [Tenants keeping up rent payments during pandemic, but wave of evictions could loom,](https://www.latimes.com/homeless-housing/story/2020-07-16/tenants-still-keep-up-rent-payments-during-coronavirus-but-wave-of-evictions-could-loom), Los Angeles Times, July 16, 2020.

Karin Brulliard and Scott Clement, [How many Americans have pets? An investigation of fuzzy statistics](https://www.washingtonpost.com/science/2019/01/31/how-many-americans-have-pets-an-investigation-into-fuzzy-statistics/?utm_term=.50f982941a55) Washington Post, January 31, 2019.

Lydia DePillis, [“This Texas military town has nearly closed the black and white homeownership gap,”](https://money.cnn.com/2018/04/17/news/economy/kileen-texas-homeownership/index.html) CNN Money, April 17, 2018.

Andrew Small, [“Map of the Day,”](https://www.citylab.com/solutions/2018/02/citylab-daily-the-quest-for-a-new-black-city/554417/) CityLab, February 27, 2018.

Leah Binkovotz, [“Where did Harvey hit Houston the hardest?”](https://www.houstonchronicle.com/local/gray-matters/article/Where-did-Harvey-hit-Houston-the-hardest-12237833.php) Houston Chronicle, September 28, 2017.

